"""empty message

Revision ID: 70bd1f9184ee
Revises: 
Create Date: 2024-02-17 20:56:00.405545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70bd1f9184ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skinType', sa.String(length=50), nullable=True),
    sa.Column('skinTone', sa.String(length=50), nullable=True),
    sa.Column('skinConditions', sa.String(length=200), nullable=True),
    sa.Column('imagePath', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    # ### end Alembic commands ###
